export const ADD_GUEST = 'ADD_GUEST'
export const EDIT_GUEST = 'EDIT_GUEST'
export const REMOVE_GUEST = 'REMOVE_GUEST'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCH_ERROR = 'FETCH_ERROR'
export const FETCH_DONE = 'FETCH_DONE'
